# Static UI deploy karne ke liye Nginx alpine ka use (Size only ~20MB)
FROM --platform=linux/amd64 nginx:alpine

# Hamari html file ko nginx ke default directory me copy karo
COPY index.html /usr/share/nginx/html/

EXPOSE 80
